code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-python.python
code --install-extension ms-azuretools.vscode-docker
code --install-extension reditorsupport.r
code --install-extension rdebugger.r-debugger
code --install-extension eamodio.gitlens
code --install-extension christian-kohler.path-intellisense
code --install-extension james-yu.latex-workshop
